version: "3.1"

services:
  postgres:
    image: postgres:13
    env_file: .env
    networks:
      - hubgrep_indexer

  redis:
    image: redis
    networks:
      - hubgrep_indexer

  hubgrep_indexer:
    build: 
      context: .
      dockerfile: Dockerfile.prod

    volumes:
      - ./results:/var/results

    restart: "${RESTART:-no}"
    mem_limit: 500m

    # uplink port to host
    ports:
      - 127.0.0.1:8081:8080

    env_file: .env
    environment:
      FLASK_APP: "/var/task/hubgrep_indexer/__init__:create_app"

    command:
      - /bin/bash
      - -c
      - |
          gunicorn --bind 0.0.0.0:8080 -c gunicorn_config.py "hubgrep_indexer:create_app()"
    tty: true
    networks:
      - hubgrep_indexer
      - hubgrep

networks:
  hubgrep_indexer:
  hubgrep:
    name: hubgrep

