version: "3.1"

services:
  postgres:
    image: postgres:13
    env_file: .env
    networks:
      - hubgrep_indexer

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - hubgrep_indexer

  hubgrep_indexer:
    build: 
      context: .
      dockerfile: Dockerfile.prod

    volumes:
      - ./results:/var/results
      - ./hosters.json:/var/task/hosters.json

    restart: "${RESTART:-no}"

    # uplink port to host
    ports:
      - 8081:8080

    env_file: .env

    command:
      - /bin/bash
      - -c
      - |
          rm -rf /tmp/metrics/
          mkdir /tmp/metrics/
          export PROMETHEUS_MULTIPROC_DIR=/tmp/metrics
          gunicorn --bind 0.0.0.0:8080 -c gunicorn_config.py "hubgrep_indexer:create_app()"
    tty: true
    networks:
      - hubgrep_indexer
      - hubgrep

  prometheus:
    image: prom/prometheus
    ports:
        - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hubgrep_indexer
      - hubgrep

networks:
  hubgrep_indexer:
  hubgrep:
    name: hubgrep

