version: "3.1"

services:

  test_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    volumes:
      - /tmp:/tmp
    networks:
      - hubgrep_indexer

  hubgrep_indexer:
    build: .
    volumes:
      - ./:/var/task
      - ./results:/var/results

    restart: "${RESTART:-no}"

    # uplink port to host
    ports:
      - 8081:8080

    env_file: .env
    environment:
      PROMETHEUS_MULTIPROC_DIR: /tmp/metrics

    command: >
      bash -ic " \
        pip install -r requirements.txt
        rm -rf /tmp/metrics/
        mkdir /tmp/metrics/
        flask run --host 0.0.0.0 --port 8080
        "
    tty: true
    networks:
      - hubgrep_indexer


networks:
  hubgrep_indexer:
