version: "3"

services:

  test_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    volumes:
      - /tmp:/tmp
    networks:
      - hubgrep_indexer

  postgres:
    image: postgres:13
    env_file: .env
    networks:
      - hubgrep_indexer

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - hubgrep_indexer

  hubgrep_indexer:
    build: .
    volumes:
      - ./:/var/task
      - ./results:/var/results

    restart: "${RESTART:-no}"

    # uplink port to host
    ports:
      - 8081:8080

    env_file: .env

    command: >
      bash -ic " \
        pip install -r requirements.txt
        flask run --host 0.0.0.0 --port 8080
        "
    tty: true
    networks:
      - hubgrep_indexer
      - hubgrep


networks:
  hubgrep_indexer:
  hubgrep:
    name: hubgrep
