version: 2.1

jobs:
  start-db:
    machine: true
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    steps:
      - checkout
      - run: touch .env
      - run: docker-compose up test_postgres
  build-and-test:
    machine: true
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    steps:
      - checkout
      - run: touch .env
      - run: docker-compose run hubgrep_indexer bash -c "pip install -r requirements.txt && ./manage.sh test"

    

    
workflows:
  main:
    jobs:
      - start-db
      - build-and-test
