version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:17.05.0-ce-git
      - image: redis
    machine: true
    steps:
      - checkout
      - run: docker run -d --name redis redis
      - run: docker build -f Dockerfile.prod -t hubgrep_indexer:test .
      - run: docker run --rm hubgrep_indexer:test /bin/bash -c "pytest"
   
    

    
workflows:
  main:
    jobs:
      - build-and-test

