version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: docker build -f Dockerfile.prod -t hubgrep:test .
      - run: docker run --rm hubgrep:test /bin/bash -c "pytest"
   
    

    
workflows:
  main:
    jobs:
      - build-and-test

