version: 2.1

jobs:
  build-and-test:
    machine: true
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
      HUBGREP_TEST_SQLALCHEMY_DATABASE_URI: postgresql://hubgrep:hubgrep@test_postgres:5432/hubgrep
    steps:
      - checkout
      - run: docker build -f Dockerfile.prod -t hubgrep_indexer:test .
      - run: docker run --rm hubgrep_indexer:test /bin/bash -c "./manage.sh test"
   
    

    
workflows:
  main:
    jobs:
      - build-and-test
