version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: touch .env
      - run: docker-compose up -d
      - run: docker-compose run hubgrep_indexer bash -c "pip install -r requirements.txt && ./manage.sh test"



    
workflows:
  main:
    jobs:
      - build-and-test
