version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: touch .env
      - run: docker-compose -f docker-compose-ci.yml up -d
      - run: docker-compose -f docker-compose-ci.yml run hubgrep_indexer bash -c "pip install -r requirements.txt && ./manage.sh test"




workflows:
  main:
    jobs:
      - build-and-test
