version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: docker build -f Dockerfile.prod -t hubgrep_indexer:test .
      - run: docker run --rm hubgrep_indexer:test /bin/bash -c "./manage.sh test"
   
    

    
workflows:
  main:
    jobs:
      - build-and-test
