version: 2.1

jobs:
  build-and-test:
    machine: true
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    steps:
      - checkout
      - run: touch .env
      - run: docker-compose up -d
      - run: sleep 30
      - run: docker ps -a
      - run: docker-compose run hubgrep_indexer bash -c "pip install -r requirements.txt && ./manage.sh test"



    
workflows:
  main:
    jobs:
      - build-and-test
