"""empty message

Revision ID: ca34729cc08b
Revises: ac02a74afc1c
Create Date: 2021-07-09 12:48:30.115799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca34729cc08b'
down_revision = 'ac02a74afc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gitea_repositories', sa.Column('html_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gitea_repositories', 'html_url')
    # ### end Alembic commands ###
