"""empty message

Revision ID: 13a4650f65a5
Revises: c135a4d3e34b
Create Date: 2021-08-22 11:39:20.848113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13a4650f65a5'
down_revision = 'c135a4d3e34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gitea_repositories', 'is_completed')
    op.drop_column('github_repositories', 'is_completed')
    op.drop_column('gitlab_repositories', 'is_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gitlab_repositories', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('github_repositories', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('gitea_repositories', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
