"""empty message

Revision ID: b01e332e2070
Revises: 
Create Date: 2021-06-12 12:02:04.153638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01e332e2070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('homepage_url', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('short_description_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('is_empty', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('stargazer_count', sa.Integer(), nullable=True),
    sa.Column('fork_coung', sa.Integer(), nullable=True),
    sa.Column('disk_usage', sa.Integer(), nullable=True),
    sa.Column('owner_login', sa.String(length=200), nullable=True),
    sa.Column('primary_language_name', sa.String(length=200), nullable=True),
    sa.Column('license_name', sa.String(length=200), nullable=True),
    sa.Column('license_nickname', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosting_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('landingpage_url', sa.String(length=500), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosting_service')
    op.drop_table('github_repository')
    # ### end Alembic commands ###
