"""empty message

Revision ID: f6ee6d5a8841
Revises: 6a58b8b65dcd
Create Date: 2021-07-04 15:02:48.034566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ee6d5a8841'
down_revision = '6a58b8b65dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosting_service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hosting_service', 'latest_export_json_gz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('latest_export_json_gz', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('export')
    # ### end Alembic commands ###
