"""empty message

Revision ID: 99c1c5ca9c91
Revises: 626658849ae6
Create Date: 2021-06-26 22:50:37.934598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99c1c5ca9c91'
down_revision = '626658849ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('latest_export_json_gz', sa.String(length=500), nullable=True))
    op.drop_column('hosting_service', 'export_url')
    op.drop_column('hosting_service', 'export_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('export_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('hosting_service', sa.Column('export_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('hosting_service', 'latest_export_json_gz')
    # ### end Alembic commands ###
