"""empty message

Revision ID: ce2939d5eaf0
Revises: b01e332e2070
Create Date: 2021-06-12 15:31:12.597460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2939d5eaf0'
down_revision = 'b01e332e2070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.add_column('hosting_service', sa.Column('export_date', sa.DateTime(timezone=500), nullable=True))
    op.add_column('hosting_service', sa.Column('export_url', sa.String(length=500), nullable=True))
    op.drop_column('hosting_service', 'config')
    op.drop_column('hosting_service', 'state')
    op.drop_column('hosting_service', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('label', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('hosting_service', sa.Column('state', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('hosting_service', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('hosting_service', 'export_url')
    op.drop_column('hosting_service', 'export_date')
    op.drop_column('hosting_service', 'api_key')
    # ### end Alembic commands ###
