"""empty message

Revision ID: 4231789d2a93
Revises: 23ee401b3cd2
Create Date: 2021-06-26 23:52:23.432914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4231789d2a93'
down_revision = '23ee401b3cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosting_service_id', sa.Integer(), nullable=False),
    sa.Column('gitlab_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('name_with_namespace', sa.String(length=500), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('path_with_namespace', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('default_branch', sa.String(length=500), nullable=True),
    sa.Column('ssh_url_to_repo', sa.String(length=500), nullable=True),
    sa.Column('http_url_to_repo', sa.String(length=500), nullable=True),
    sa.Column('web_url', sa.String(length=500), nullable=True),
    sa.Column('readme_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('forks_count', sa.String(length=500), nullable=True),
    sa.Column('star_count', sa.String(length=500), nullable=True),
    sa.Column('user_name', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('repo_ident_index_gitlab', 'gitlab_repositories', ['id', 'gitlab_id'], unique=False)
    op.drop_table('gitlab_repository')
    op.create_index('repo_ident_index_gitea', 'gitea_repositories', ['id', 'gitea_id'], unique=False)
    op.create_index('repo_ident_index_github', 'github_repositories', ['id', 'github_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('repo_ident_index_github', table_name='github_repositories')
    op.drop_index('repo_ident_index_gitea', table_name='gitea_repositories')
    op.create_table('gitlab_repository',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hosting_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gitlab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name_with_namespace', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('path_with_namespace', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('default_branch', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ssh_url_to_repo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('http_url_to_repo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('web_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('readme_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('forks_count', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('star_count', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], name='gitlab_repository_hosting_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gitlab_repository_pkey')
    )
    op.drop_index('repo_ident_index_gitlab', table_name='gitlab_repositories')
    op.drop_table('gitlab_repositories')
    # ### end Alembic commands ###
