"""empty message

Revision ID: ac02a74afc1c
Revises: 40aefa3ed33d
Create Date: 2021-07-08 20:35:31.907245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac02a74afc1c'
down_revision = '40aefa3ed33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('is_raw', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'is_raw')
    # ### end Alembic commands ###
