"""empty message

Revision ID: d4a94134ab13
Revises: 714fde2ae0f7
Create Date: 2021-07-14 22:29:28.667305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a94134ab13'
down_revision = '714fde2ae0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('repo_ident_index_gitea', table_name='gitea_repositories')
    op.drop_index('repo_ident_index_gitlab', table_name='gitlab_repositories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('repo_ident_index_gitlab', 'gitlab_repositories', ['hosting_service_id', 'gitlab_id'], unique=False)
    op.create_index('repo_ident_index_gitea', 'gitea_repositories', ['hosting_service_id', 'gitea_id'], unique=False)
    # ### end Alembic commands ###
