"""empty message

Revision ID: 40aefa3ed33d
Revises: 6858f51168fd
Create Date: 2021-07-05 19:24:05.080676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40aefa3ed33d'
down_revision = '6858f51168fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('repo_ident_index_gitea', table_name='gitea_repositories')
    op.create_index('repo_ident_index_gitea', 'gitea_repositories', ['hosting_service_id', 'gitea_id'], unique=False)
    op.drop_index('repo_ident_index_github', table_name='github_repositories')
    op.create_index('repo_ident_index_github', 'github_repositories', ['hosting_service_id', 'github_id'], unique=False)
    op.drop_index('repo_ident_index_gitlab', table_name='gitlab_repositories')
    op.create_index('repo_ident_index_gitlab', 'gitlab_repositories', ['hosting_service_id', 'gitlab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('repo_ident_index_gitlab', table_name='gitlab_repositories')
    op.create_index('repo_ident_index_gitlab', 'gitlab_repositories', ['id', 'gitlab_id'], unique=False)
    op.drop_index('repo_ident_index_github', table_name='github_repositories')
    op.create_index('repo_ident_index_github', 'github_repositories', ['id', 'github_id'], unique=False)
    op.drop_index('repo_ident_index_gitea', table_name='gitea_repositories')
    op.create_index('repo_ident_index_gitea', 'gitea_repositories', ['id', 'gitea_id'], unique=False)
    # ### end Alembic commands ###
