"""empty message

Revision ID: c135a4d3e34b
Revises: c4ba9189fc42
Create Date: 2021-08-06 10:11:50.885560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c135a4d3e34b'
down_revision = 'c4ba9189fc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosting_service', 'api_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=500)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosting_service', 'api_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=500)),
               nullable=True)
    # ### end Alembic commands ###
