"""empty message

Revision ID: 714fde2ae0f7
Revises: ca34729cc08b
Create Date: 2021-07-14 22:28:44.285555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714fde2ae0f7'
down_revision = 'ca34729cc08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gitea_repositories', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('github_repositories', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.drop_index('repo_ident_index_github', table_name='github_repositories')
    op.add_column('gitlab_repositories', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gitlab_repositories', 'is_completed')
    op.create_index('repo_ident_index_github', 'github_repositories', ['hosting_service_id', 'github_id'], unique=False)
    op.drop_column('github_repositories', 'is_completed')
    op.drop_column('gitea_repositories', 'is_completed')
    # ### end Alembic commands ###
