"""empty message

Revision ID: c4ba9189fc42
Revises: a8d7cb59fbba
Create Date: 2021-08-02 11:11:30.107384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4ba9189fc42'
down_revision = 'a8d7cb59fbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gitea_repositories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               autoincrement=True)
    op.alter_column('github_repositories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               autoincrement=True)
    op.alter_column('gitlab_repositories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gitlab_repositories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               autoincrement=True)
    op.alter_column('github_repositories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               autoincrement=True)
    op.alter_column('gitea_repositories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               autoincrement=True)
    # ### end Alembic commands ###
