"""empty message

Revision ID: 93d1e46ffb46
Revises: d4a94134ab13
Create Date: 2021-07-16 20:52:37.634514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d1e46ffb46'
down_revision = 'd4a94134ab13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosting_service_id', sa.Integer(), nullable=False),
    sa.Column('is_raw', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('repo_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('export')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hosting_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('repo_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_raw', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], name='export_hosting_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='export_pkey')
    )
    op.drop_table('export_meta')
    # ### end Alembic commands ###
