"""empty message

Revision ID: 34c8e968cb5c
Revises: eb95e3514697
Create Date: 2021-01-02 20:45:03.184133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c8e968cb5c'
down_revision = 'eb95e3514697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Integer(), nullable=False),
    sa.Column('gh_login', sa.String(length=128), nullable=True),
    sa.Column('gh_id', sa.Integer(), nullable=True),
    sa.Column('gh_node_id', sa.String(length=24), nullable=True),
    sa.Column('gh_type', sa.String(length=12), nullable=True),
    sa.Column('gh_site_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['platform'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_users')
    # ### end Alembic commands ###
