"""empty message

Revision ID: 453d4e6bb386
Revises: 5dcf96093248
Create Date: 2021-01-02 21:06:01.073025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453d4e6bb386'
down_revision = '5dcf96093248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('state', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'state')
    # ### end Alembic commands ###
