"""empty message

Revision ID: 5dcf96093248
Revises: 34c8e968cb5c
Create Date: 2021-01-02 20:58:30.892388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcf96093248'
down_revision = '34c8e968cb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_users', 'gh_node_id',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_users', 'gh_node_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###
