"""empty message

Revision ID: a0810e49518c
Revises: 453d4e6bb386
Create Date: 2021-01-03 02:05:38.023170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0810e49518c'
down_revision = '453d4e6bb386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('github_user_idx', 'github_users', ['platform', 'gh_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('github_user_idx', table_name='github_users')
    # ### end Alembic commands ###
