"""empty message

Revision ID: eb95e3514697
Revises: 2892599d694e
Create Date: 2021-01-02 19:50:10.944098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb95e3514697'
down_revision = '2892599d694e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('platform_type', sa.String(length=128), nullable=True))
    op.drop_column('platforms', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('platforms', 'platform_type')
    # ### end Alembic commands ###
